import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'SocialPulse - Social Analytics SAAS',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
